/**
 * @file session_manager.cpp
 * @brief Orchestrates the high-level state machine for OtterSec secure
 * streaming.
 *
 * The SessionManager is responsible for transitioning the system between its
 * core states (IDLE, HANDSHAKING, STREAMING, TEARDOWN). It bridges the gap
 * between the TLS Handshake Server and the GStreamer UDP pipeline, ensuring
 * that cryptographic keys are safely passed and video only flows when secured.
 */
#include "session_manager.hpp"
#include "control_server.hpp"
#include <iostream>

namespace ottersec {
/** External reference to the global ControlServer to fetch the dynamic client
 * IP. */
extern std::unique_ptr<ControlServer> g_control_server;

/**
 * @brief Constructs a new SessionManager object.
 *
 * Extracts the handshake port, certificate path, and private key path from
 * the provided configuration. Falls back to default values (8443, "server.crt",
 * "server.key") if the configuration is null or incomplete.
 *
 * @param config Pointer to the user-defined handshake configuration.
 */
SessionManager::SessionManager(const OtterHandshakeConfig *config) {
  handshake_port_ = config ? config->handshake_port : 8443;

  cert_path_ = (config && config->cert_path) ? config->cert_path : "server.crt";
  key_path_ = (config && config->key_path) ? config->key_path : "server.key";
}

/**
 * @brief Destroys the SessionManager object, ensuring a safe shutdown.
 */
SessionManager::~SessionManager() { shutdown(); }

/**
 * @brief Initiates the secure connection process upon detecting a fall.
 *
 * Transitions the system from IDLE to HANDSHAKING. Spins up the TLS
 * HandshakeServer and binds an asynchronous callback to handle the generated
 * cryptographic keys once the client successfully authenticates.
 *
 * @param event Pointer to the fall event metadata.
 * @return true if the handshake process was successfully started.
 * @return false if the system is not in the IDLE state (e.g., already
 * streaming).
 */
bool SessionManager::trigger_fall_event(const OtterFallEvent *event) {
  std::lock_guard<std::mutex> lock(state_mutex_);
  if (current_state_ != State::IDLE)
    return false;

  std::cout << "[OtterSec] Fall Detected! Triggering Handshake.\n";
  transition_to(State::HANDSHAKING);

  server_ =
      std::make_unique<HandshakeServer>(handshake_port_, cert_path_, key_path_);

  server_->start([this](bool success, const std::vector<uint8_t> &key,
                        const std::vector<uint8_t> &salt) {
    this->on_handshake_complete(success, key, salt);
  });

  return true;
}

/**
 * @brief Callback fired when the TLS HandshakeServer finishes negotiation.
 *
 * If successful, securely stores the SRTP keys in memory, fetches the client's
 * dynamic IP address from the global control server, spins up the GStreamer
 * pipeline, and transitions to the STREAMING state.
 *
 * @param success True if the TLS handshake completed and keys were generated.
 * @param key The 16-byte SRTP cryptographic key.
 * @param salt The 14-byte SRTP cryptographic salt.
 */
void SessionManager::on_handshake_complete(bool success,
                                           const std::vector<uint8_t> &key,
                                           const std::vector<uint8_t> &salt) {
  std::lock_guard<std::mutex> lock(state_mutex_);
  if (success) {
    std::cout << "[OtterSec] Handshake Success. Securing keys in memory.\n";
    sec_context_.set_keys(key.data(), key.size(), salt.data(), salt.size());

    std::string target_ip = g_control_server->active_client_ip;
    if (target_ip.empty())
      target_ip = "127.0.0.1";

    pipeline_.start(target_ip, 5004, key, salt);

    transition_to(State::STREAMING);
  } else {
    std::cout << "[OtterSec] Handshake Failed. Tearing down.\n";
    transition_to(State::TEARDOWN);
  }
}

/**
 * @brief Pushes a raw video frame to the pipeline if the session is active.
 *
 * @param frame Pointer to the raw video buffer generated by EdgeStreamer.
 * @return true if the frame was successfully pushed to GStreamer.
 * @return false if the system is not in the STREAMING state, or pushing fails.
 */
bool SessionManager::push_frame(const OtterFrameBuffer *frame) {
  std::lock_guard<std::mutex> lock(state_mutex_);
  if (current_state_ != State::STREAMING)
    return false;

  return pipeline_.push_frame(frame);
}

/**
 * @brief Halts the streaming session and cleans up all resources.
 *
 * Transitions to TEARDOWN, stops the TLS server, wipes the cryptographic
 * keys from memory, stops the GStreamer pipeline, and resets to IDLE.
 */
void SessionManager::shutdown() {
  std::lock_guard<std::mutex> lock(state_mutex_);
  if (current_state_ == State::IDLE)
    return;

  transition_to(State::TEARDOWN);
  if (server_)
    server_->stop();
  sec_context_.clear();

  pipeline_.stop();

  transition_to(State::IDLE);
}

/**
 * @brief Helper function to update the internal state machine.
 *
 * @param new_state The target state to transition to.
 */
void SessionManager::transition_to(State new_state) {
  current_state_ = new_state;
}

} // namespace ottersec
